name: Swirl
description: Dart servers made with love.
version: 0.0.3
author: Frederico Bittencourt <fred.rbittencourt@gmail.com>

environment:
  sdk: '>=1.0.0 <2.0.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
